### ISSUE TITLE
Error when trying to update from free to premium plan

### ISSUE THREAD

**Issue by zacharyinserra** [andrewmcodes/455ProjectManagementApp#47]
### Steps to Reproduce

**Comment by andrewmcodes** [comment]
# Error log:
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
# Heroku Log
```

2018-04-27T02:16:19.143653+00:00 heroku[router]: at=info method=GET path="/" host=projectmanagement455.herokuapp.com request_id=8369ffa6-466f-48ed-8e60-8992d0de51af fwd="173.93.10.129" dyno=web.1 connect=0ms service=122ms status=200 bytes=4050 protocol=https
2018-04-27T02:16:22.711871+00:00 app[web.1]: I, [2018-04-27T02:16:22.711744 #4]  INFO -- : [c671ec67-b4c7-4ccb-8337-a498380f073f] Started GET "/plan/edit" for 173.93.10.129 at 2018-04-27 02:16:22 +0000
2018-04-27T02:16:22.713214+00:00 app[web.1]: I, [2018-04-27T02:16:22.713130 #4]  INFO -- : [c671ec67-b4c7-4ccb-8337-a498380f073f] Processing by TenantsController#edit as HTML
2018-04-27T02:16:22.729394+00:00 app[web.1]: D, [2018-04-27T02:16:22.729253 #4] DEBUG -- : [c671ec67-b4c7-4ccb-8337-a498380f073f]   [1m[36mUser Load (6.8ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE (users.tenant_id IS NULL) AND "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
2018-04-27T02:16:22.739102+00:00 app[web.1]: D, [2018-04-27T02:16:22.738946 #4] DEBUG -- : [c671ec67-b4c7-4ccb-8337-a498380f073f]   [1m[36mTenant Load (6.3ms)[0m  [1m[34mSELECT  "tenants".* FROM "tenants" INNER JOIN "tenants_users" ON "tenants"."id" = "tenants_users"."tenant_id" WHERE (tenants.tenant_id IS NULL) AND "tenants_users"."user_id" = $1 ORDER BY "tenants"."id" ASC LIMIT $2[0m  [["user_id", 1], ["LIMIT", 1]]
2018-04-27T02:16:22.739587+00:00 app[web.1]: D, [2018-04-27T02:16:22.739509 #4] DEBUG -- : [c671ec67-b4c7-4ccb-8337-a498380f073f] MILIA >>>>> [change tenant] new: 1	old: %
2018-04-27T02:16:22.747166+00:00 app[web.1]: D, [2018-04-27T02:16:22.747041 #4] DEBUG -- : [c671ec67-b4c7-4ccb-8337-a498380f073f]   [1m[36mTenant Load (6.4ms)[0m  [1m[34mSELECT  "tenants".* FROM "tenants" WHERE (tenants.tenant_id IS NULL) AND "tenants"."id" = $1 LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
2018-04-27T02:16:22.751155+00:00 app[web.1]: I, [2018-04-27T02:16:22.750519 #4]  INFO -- : [c671ec67-b4c7-4ccb-8337-a498380f073f]   Rendering tenants/edit.html.haml within layouts/application
2018-04-27T02:16:22.780524+00:00 app[web.1]: D, [2018-04-27T02:16:22.780380 #4] DEBUG -- : [c671ec67-b4c7-4ccb-8337-a498380f073f]   [1m[36mPayment Load (2.4ms)[0m  [1m[34mSELECT  "payments".* FROM "payments" WHERE "payments"."tenant_id" = $1 LIMIT $2[0m  [["tenant_id", 1], ["LIMIT", 1]]
2018-04-27T02:16:22.785712+00:00 app[web.1]: I, [2018-04-27T02:16:22.785614 #4]  INFO -- : [c671ec67-b4c7-4ccb-8337-a498380f073f]   Rendered tenants/edit.html.haml within layouts/application (34.4ms)
2018-04-27T02:16:22.792066+00:00 app[web.1]: I, [2018-04-27T02:16:22.791975 #4]  INFO -- : [c671ec67-b4c7-4ccb-8337-a498380f073f]   Rendered common/_navbar.html.haml (0.8ms)
2018-04-27T02:16:22.792730+00:00 app[web.1]: I, [2018-04-27T02:16:22.792531 #4]  INFO -- : [c671ec67-b4c7-4ccb-8337-a498380f073f] Completed 200 OK in 79ms (Views: 32.9ms | ActiveRecord: 30.7ms)
2018-04-27T02:16:22.792916+00:00 app[web.1]: I, [2018-04-27T02:16:22.792836 #4]  INFO -- : [c671ec67-b4c7-4ccb-8337-a498380f073f] Oink Action: tenants#edit
2018-04-27T02:16:22.793065+00:00 app[web.1]: I, [2018-04-27T02:16:22.792996 #4]  INFO -- : [c671ec67-b4c7-4ccb-8337-a498380f073f] Memory usage: 1097956 | PID: 4
2018-04-27T02:16:22.793177+00:00 app[web.1]: I, [2018-04-27T02:16:22.793104 #4]  INFO -- : [c671ec67-b4c7-4ccb-8337-a498380f073f] Instantiation Breakdown: Total: 3 | Tenant: 2 | User: 1
2018-04-27T02:16:22.793253+00:00 app[web.1]: I, [2018-04-27T02:16:22.793187 #4]  INFO -- : [c671ec67-b4c7-4ccb-8337-a498380f073f] Oink Log Entry Complete
2018-04-27T02:16:22.794741+00:00 heroku[router]: at=info method=GET path="/plan/edit" host=projectmanagement455.herokuapp.com request_id=c671ec67-b4c7-4ccb-8337-a498380f073f fwd="173.93.10.129" dyno=web.1 connect=0ms service=87ms status=200 bytes=6414 protocol=https
2018-04-27T02:16:28.325485+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=projectmanagement455.herokuapp.com request_id=a72681e9-a87f-4a84-997d-9cabfcdad75a fwd="173.93.10.129" dyno=web.1 connect=0ms service=1ms status=304 bytes=48 protocol=https
2018-04-27T02:16:38.275547+00:00 app[web.1]: I, [2018-04-27T02:16:38.275394 #4]  INFO -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06] Started PATCH "/plan/update" for 173.93.10.129 at 2018-04-27 02:16:38 +0000
2018-04-27T02:16:38.276986+00:00 app[web.1]: I, [2018-04-27T02:16:38.276832 #4]  INFO -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06] Processing by TenantsController#update as HTML
2018-04-27T02:16:38.277127+00:00 app[web.1]: I, [2018-04-27T02:16:38.277030 #4]  INFO -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"erabrG7umnG3Q641wYLzsTZOfandyTRbyah9k9FZZMRuKntJIK/CxKe6mAdTRCnTYpw3VXwmyJCoaSKetlIpBg==", "tenant"=>{"name"=>"N2 Publishing", "plan"=>"premium"}, "payment"=>{"card_number"=>"4242424242424242", "card_cvv"=>"123", "card_expires_month"=>"2", "card_expires_year"=>"2020"}}
2018-04-27T02:16:38.295233+00:00 app[web.1]: D, [2018-04-27T02:16:38.295081 #4] DEBUG -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06]   [1m[36mUser Load (3.7ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE (users.tenant_id IS NULL) AND "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
2018-04-27T02:16:38.300696+00:00 app[web.1]: D, [2018-04-27T02:16:38.300602 #4] DEBUG -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06]   [1m[36mTenant Load (2.5ms)[0m  [1m[34mSELECT "tenants".* FROM "tenants" INNER JOIN "tenants_users" ON "tenants"."id" = "tenants_users"."tenant_id" WHERE (tenants.tenant_id IS NULL) AND "tenants_users"."user_id" = $1[0m  [["user_id", 1]]
2018-04-27T02:16:38.301096+00:00 app[web.1]: D, [2018-04-27T02:16:38.301014 #4] DEBUG -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06] MILIA >>>>> [change tenant] new: 1	old: %
2018-04-27T02:16:38.306896+00:00 app[web.1]: D, [2018-04-27T02:16:38.306793 #4] DEBUG -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06]   [1m[36mTenant Load (4.9ms)[0m  [1m[34mSELECT  "tenants".* FROM "tenants" WHERE (tenants.tenant_id IS NULL) AND "tenants"."id" = $1 LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
2018-04-27T02:16:38.308848+00:00 app[web.1]: D, [2018-04-27T02:16:38.308760 #4] DEBUG -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06]   [1m[35m (1.4ms)[0m  [1m[35mBEGIN[0m
2018-04-27T02:16:38.312850+00:00 app[web.1]: D, [2018-04-27T02:16:38.312749 #4] DEBUG -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06]   [1m[36mTenant Exists (1.7ms)[0m  [1m[34mSELECT  1 AS one FROM "tenants" WHERE "tenants"."name" = $1 AND "tenants"."id" != $2 LIMIT $3[0m  [["name", "N2 Publishing"], ["id", 1], ["LIMIT", 1]]
2018-04-27T02:16:38.318937+00:00 app[web.1]: D, [2018-04-27T02:16:38.318839 #4] DEBUG -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06]   [1m[36mTenant Update (4.3ms)[0m  [1m[33mUPDATE "tenants" SET "plan" = $1, "updated_at" = $2 WHERE "tenants"."id" = $3[0m  [["plan", "premium"], ["updated_at", "2018-04-27 02:16:38.313236"], ["id", 1]]
2018-04-27T02:16:38.322748+00:00 app[web.1]: D, [2018-04-27T02:16:38.322655 #4] DEBUG -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06]   [1m[36mPayment Load (2.2ms)[0m  [1m[34mSELECT  "payments".* FROM "payments" WHERE "payments"."tenant_id" = $1 LIMIT $2[0m  [["tenant_id", 1], ["LIMIT", 1]]
2018-04-27T02:16:39.378177+00:00 heroku[router]: at=info method=POST path="/plan/update" host=projectmanagement455.herokuapp.com request_id=0c623762-0ef8-4971-9b07-ffcad9b2eb06 fwd="173.93.10.129" dyno=web.1 connect=0ms service=1105ms status=500 bytes=1827 protocol=https
2018-04-27T02:16:39.343582+00:00 app[web.1]: D, [2018-04-27T02:16:39.343442 #4] DEBUG -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06]   [1m[36mTenant Exists (5.2ms)[0m  [1m[34mSELECT  1 AS one FROM "tenants" WHERE "tenants"."name" = $1 AND "tenants"."id" != $2 LIMIT $3[0m  [["name", "N2 Publishing"], ["id", 1], ["LIMIT", 1]]
2018-04-27T02:16:39.360944+00:00 app[web.1]: D, [2018-04-27T02:16:39.360436 #4] DEBUG -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06]   [1m[36mTenant Update (15.0ms)[0m  [1m[33mUPDATE "tenants" SET "plan" = $1, "updated_at" = $2 WHERE "tenants"."id" = $3[0m  [["plan", "free"], ["updated_at", "2018-04-27 02:16:39.343982"], ["id", 1]]
2018-04-27T02:16:39.373932+00:00 app[web.1]: D, [2018-04-27T02:16:39.373782 #4] DEBUG -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06]   [1m[35m (5.4ms)[0m  [1m[31mROLLBACK[0m
2018-04-27T02:16:39.374993+00:00 app[web.1]: I, [2018-04-27T02:16:39.374908 #4]  INFO -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06] Completed 500 Internal Server Error in 1098ms (ActiveRecord: 50.1ms)
2018-04-27T02:16:39.376488+00:00 app[web.1]: F, [2018-04-27T02:16:39.376420 #4] FATAL -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06]   
2018-04-27T02:16:39.376693+00:00 app[web.1]: F, [2018-04-27T02:16:39.376569 #4] FATAL -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06] ActionView::MissingTemplate (Missing template tenants/1/edit with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :haml, :jbuilder]}. Searched in:
2018-04-27T02:16:39.376696+00:00 app[web.1]:   * "/app/app/views"
2018-04-27T02:16:39.376698+00:00 app[web.1]:   * "/app/vendor/bundle/ruby/2.4.0/gems/devise-bootstrap-views-0.0.11/app/views"
2018-04-27T02:16:39.376699+00:00 app[web.1]:   * "/app/vendor/bundle/ruby/2.4.0/gems/devise-4.4.3/app/views"
2018-04-27T02:16:39.376701+00:00 app[web.1]: ):
2018-04-27T02:16:39.377020+00:00 app[web.1]: F, [2018-04-27T02:16:39.376949 #4] FATAL -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06]   
2018-04-27T02:16:39.377351+00:00 app[web.1]: F, [2018-04-27T02:16:39.377281 #4] FATAL -- : [0c623762-0ef8-4971-9b07-ffcad9b2eb06] app/controllers/tenants_controller.rb:24:in `rescue in block (2 levels) in update'
2018-04-27T02:16:39.377354+00:00 app[web.1]: [0c623762-0ef8-4971-9b07-ffcad9b2eb06] app/controllers/tenants_controller.rb:16:in `block (2 levels) in update'
2018-04-27T02:16:39.377356+00:00 app[web.1]: [0c623762-0ef8-4971-9b07-ffcad9b2eb06] app/controllers/tenants_controller.rb:10:in `block in update'
2018-04-27T02:16:39.377358+00:00 app[web.1]: [0c623762-0ef8-4971-9b07-ffcad9b2eb06] app/controllers/tenants_controller.rb:9:in `update'
2018-04-27T02:16:40.894085+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=projectmanagement455.herokuapp.com request_id=2f002ed3-5274-4d72-afed-5d90ae5c4f63 fwd="173.93.10.129" dyno=web.1 connect=0ms service=6ms status=304 bytes=48 protocol=https
```

**Comment by andrewmcodes** [comment]
Still having issues with the change plan form. Not sure if it has to do with the JS or Ruby but it works in development. I will continue to investigate..
