### ISSUE TITLE
Aws::S3::Errors::InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.

### ISSUE THREAD

**Issue by andrewmcodes** [andrewmcodes/455ProjectManagementApp#8]
https://sentry.io/uncw/rails/issues/492636982/

```
Aws::S3::Errors::InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
  app/models/artifact.rb:30:in `upload_to_s3'
    obj.upload_file(upload.path, acl:'public-read')
  app/controllers/artifacts_controller.rb:32:in `block in create'
    if @artifact.save
  app/controllers/artifacts_controller.rb:31:in `create'
    respond_to do |format|
...
(115 additional frame(s) were not displayed)

Aws::S3::Errors::InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
```

**Comment by andrewmcodes** [comment]
Apparently there was some sort of error with the way the AWS service was setup. Will need to go back in and fix those issues in the AWS console.

**Comment by andrewmcodes** [comment]
Looks like AWS account was suspended due to some security issue and not replying to their email after dealing with the security issue. I have reached out to their support team to hopefully take care of this issue.
